language: c

compiler:
  - gcc
  - clang

env:
    - CONF="--disable-test-perf"
    - CONF="--disable-abi-compat --disable-test-perf"

build:
  ci:
    - apt-get update
    - apt-get install --no-install-recommends -yy asciidoctor autoconf automake build-essential ccache clang doxygen gcc graphviz libconfig-dev libcunit1-dev libnuma-dev libpcap-dev libssl-dev libtool mscgen xsltproc
    - mkdir -p $HOME/odp-shmdir
    - export CI=true ODP_SHM_DIR=$HOME/odp-shmdir ODP_TEST_OUT_XML=yes
    - ./bootstrap
    - if [ "${CC#clang}" != "${CC}" ] ; then export CXX="${CC/clang/clang++}"; fi
    - echo ./configure $CONF
    - ./configure $CONF
    - make -j $(nproc)
    - ODP_SCHEDULER=basic make check
    - ./scripts/shippable-post.sh basic
    - ODP_SCHEDULER=sp make check
    - ./scripts/shippable-post.sh sp
    - ODP_SCHEDULER=scalable make check
    - ./scripts/shippable-post.sh scalable
    - rm -rf $HOME/odp-shmdir

  on_failure:
    - ./scripts/shippable-post.sh
    - cat config.log
    - find . -name "*.trs" | xargs grep -l '^.test-result. FAIL' | while read trs ; do echo FAILURE detected at $trs; cat ${trs%%.trs}.log ; done
